# Site Configuration

# Theme, mapped to the directory: ./theme/xxxx
theme: default

# HTML Language setting
lang: "en"

# Plugins, implemented in ./plugins/PLUGIN_NAME
# Use {{ vars.PLUGIN_NAME }} in the settings below

# The output of the plugin can be used below, e.g., {{vars.MediumFollowersCountPlugin}}
plugins:
  # Automatically fetch Medium follower count
  # - MediumFollowersCountPlugin:
  #     username: zhgchgli
  # # Automatically fetch Github repo star count
  # - GithubRepoStarsCountPlugin:
  #     - ZhgChgLi/ZMarkupParser
  #     - ZhgChgLi/ZReviewTender
  #     - ZhgChgLi/ZMediumToMarkdown
  #     - ZhgChgLi/linkyee

# Google Analytics tracking id
google_analytics_id:

# HTML Title
title: "Vasco C. B. Ferreira"

# Avatar image path
avatar: "./images/profile.jpeg"

# Name section text
name: "Vasco C. B. Ferreira"

# Tagline section text
tagline: >-
  Master of Physics student at KU Leuven. Working on Vlassov plasma simulations for my Thesis
# List of links
# icon: Use Font Awesome icons (https://fontawesome.com/search?o=r&m=free)
# text: The displayed text for the link
# title: The url title
# url: The URL of the link
# alt: Alternative text for accessibility
# target: `_blank` opens in a new tab, `_self` opens in the same frame

# Link example
# links:
#   - link:
#       icon: "fa-brands fa-medium"
#       text: "Tech Blog <span class='link-button-text'>({{vars.MediumFollowersCountPlugin}} Followers)</span>"
#       url: "https://blog.zhgchg.li"
#       alt: "ZhgChgLi's Tech Blog"
#       title: "ZhgChgLi's Tech Blog"
#       target: "_blank"

# List of social media links
# icon: Use Font Awesome icons (https://fontawesome.com/search?o=r&m=free)
# title: The url title
# url: The URL of the social media link
# alt: Alternative text for accessibility
# target: _blank opens in a new tab, _self opens in the same frame


# Socials example
# socials:
#   - social:
#       icon: "fa-brands fa-medium"
#       url: "https://blog.zhgchg.li"
#       title: "ZhgChgLi's Medium"
#       alt: "ZhgChgLi's Medium"
#       target: "_blank"

# Footer text
footer: >
  Feel free to contact me. Never stop being curious!
# Footer copyright message
# Linkyee is a 100% free, open-source project—feel free to modify the copyright message as you like. :)
copyright: >
  © 2024  Powered by <a href="https://github.com/ZhgChgLi/linkyee" target="_blank">linkyee</a>
